# Generated by Django 4.0.4 on 2022-04-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_dependent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lawyer_domain',
            name='id',
        ),
        migrations.AlterField(
            model_name='client_dependent',
            name='ClientEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.client'),
        ),
        migrations.AlterField(
            model_name='lawyer_domain',
            name='LawyerEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.lawyer'),
        ),
        migrations.AddConstraint(
            model_name='client_dependent',
            constraint=models.UniqueConstraint(fields=('ClientEmail', 'DependentName'), name='dependent_client'),
        ),
        migrations.AddConstraint(
            model_name='lawyer_domain',
            constraint=models.UniqueConstraint(fields=('LawyerEmail', 'Domain'), name='domain_lawyer'),
        ),
    ]
