# Generated by Django 4.0.4 on 2022-04-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_client_dependent_id_remove_lawyer_domain_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='DefenseLawyerEmail',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='DefenseLawyer', to='dashboard.lawyer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='ProsecutorLawyerEmail',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ProsecutorLawyer', to='dashboard.lawyer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='LawyerEmail',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lawyer'),
        ),
        migrations.AlterField(
            model_name='client_dependent',
            name='ClientEmail',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.client'),
        ),
        migrations.AlterField(
            model_name='lawyer_domain',
            name='LawyerEmail',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.lawyer'),
        ),
    ]
