# Generated by Django 4.0.4 on 2022-04-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_case_judgeid_case_judgeemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='JudgeEmail',
            field=models.ForeignKey(db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.judge'),
        ),
        migrations.AlterField(
            model_name='case',
            name='Verdict',
            field=models.CharField(default=0, max_length=45, null=True),
        ),
    ]
