# Generated by Django 4.0.4 on 2022-04-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_case_judgeemail_alter_case_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='DefenseClientEmail',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='DefenseClient', to='dashboard.client'),
        ),
        migrations.AddField(
            model_name='case',
            name='ProsecutorClientEmail',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ProsecutorClient', to='dashboard.client'),
        ),
    ]
