# Generated by Django 4.0.4 on 2022-04-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_case_defenseclientemail_case_prosecutorclientemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='JudgeEmail',
        ),
    ]
